# Site settings
title: Open ONI (Open Online Newspaper Initiative)
email: kdalziel2@unl.edu
description: > # this means to ignore newlines until "baseurl:"
    Main page for Open ONI software.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://open-oni.github.io/" # the base hostname & protocol for your site
# twitter_username: CDRH_UNL
github_username:  open-oni

# Gems
gems:
  - jekyll-paginate
  - jekyll-redirect-from

# Build settings
markdown: kramdown
paginate: 5               # number of posts per page
paginate_path: "/:num/"
